// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAgNEpiygJgHzdl0kxZ9eTGXiLkNWypnPM',
    appId: '1:389265001444:web:61b5484eb7ad8d58e3d5f1',
    messagingSenderId: '389265001444',
    projectId: 'live-share-b953a',
    authDomain: 'live-share-b953a.firebaseapp.com',
    storageBucket: 'live-share-b953a.appspot.com',
    measurementId: 'G-MCN59K9NHG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDWAwo0Q1Js75bWwh4t-NZ-jTE9bP1iC8A',
    appId: '1:389265001444:android:e2a65ea7c3d6a9b1e3d5f1',
    messagingSenderId: '389265001444',
    projectId: 'live-share-b953a',
    storageBucket: 'live-share-b953a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCp8vYWaPScN2kBfzJM0NQDCAFqCZyYPDk',
    appId: '1:389265001444:ios:82b46bd4c40ff3d2e3d5f1',
    messagingSenderId: '389265001444',
    projectId: 'live-share-b953a',
    storageBucket: 'live-share-b953a.appspot.com',
    iosClientId: '389265001444-b673668f156ndh0fqpomhinrvn1gt1ho.apps.googleusercontent.com',
    iosBundleId: 'com.example.liveShare',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCp8vYWaPScN2kBfzJM0NQDCAFqCZyYPDk',
    appId: '1:389265001444:ios:82b46bd4c40ff3d2e3d5f1',
    messagingSenderId: '389265001444',
    projectId: 'live-share-b953a',
    storageBucket: 'live-share-b953a.appspot.com',
    iosClientId: '389265001444-b673668f156ndh0fqpomhinrvn1gt1ho.apps.googleusercontent.com',
    iosBundleId: 'com.example.liveShare',
  );
}
